### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by nonoguynono** [robertvazan/sourceafis-net#12]
i get this notification when i run it
![Screenshot 2021-09-04 161832](https://user-images.githubusercontent.com/77421947/132108303-f8ce7a79-8c21-41f1-bb20-67ec21bb2e06.png)

**Comment by robertvazan** [comment]
SourceAFIS is a library. You are supposed to build an application around it. See the tutorial:

https://sourceafis.machinezoo.com/net
