### ISSUE TITLE
Fail to visualize the block orientation

### ISSUE THREAD

**Issue by michealChin** [robertvazan/sourceafis-net#13]
Hi, 

First I am appreciated with your great effort on this project with all the detail explanation on the algorithm. However I am not able to display the Smoothed orientation correctly like [https://sourceafis.machinezoo.com/transparency/smoothed-orientation] 
![image](https://user-images.githubusercontent.com/12890191/147334085-9456a60c-5964-4665-90fb-f8280229592d.png)
, here is what I get 
![image](https://user-images.githubusercontent.com/12890191/147333714-3fe04cd7-3595-4c7d-8564-767a4d57139c.png)

I try to visualize the block orientation base on the highlighted property
![image](https://user-images.githubusercontent.com/12890191/147334394-e0a668e7-6a6d-4a09-b441-cd3f257a5ae1.png)

As you can see from the highlighted part in the attached image, the angle after converted from radian (4.6509223) to degree is around 265 and the angle seems in the opposite direction if compare to the background fingerprint image. FYI I use the probe.png that come along with this source code as the fingerprint sample. May I know what am I doing wrong in visualizing the block orientation?

**Comment by robertvazan** [comment]
I think you are treating orientation angles as direction angles. Docs for [smoothed-orientation](https://sourceafis.machinezoo.com/transparency/smoothed-orientation) link to [pixelwise-orientation](https://sourceafis.machinezoo.com/transparency/pixelwise-orientation) page, which explains the difference.

Feel free to reopen the issue if this does not fix it.

**Comment by michealChin** [comment]
I see, May I know how to convert orientation angle into direction angle? I have go through the pixelwise-orientation page but still not quite understand the concept of orientation angle? Or can you share me any reference on how to convert orientation angle into direction angle? Thanks in advance!

**Comment by robertvazan** [comment]
See [DoubleAngle.cs](https://github.com/robertvazan/sourceafis-net/blob/master/SourceAFIS/DoubleAngle.cs), methods `ToOrientation` and `FromOrientation`.

**Comment by michealChin** [comment]
> See [DoubleAngle.cs](https://github.com/robertvazan/sourceafis-net/blob/master/SourceAFIS/DoubleAngle.cs), methods `ToOrientation` and `FromOrientation`.

Perfect! It is working now.
