### ISSUE TITLE
The name 'Files' does not exist in the current context

### ISSUE THREAD

**Issue by ImAshrivastava** [robertvazan/sourceafis-net#14]
Have no prior experience with c# at all. I am having a hard time setting up. 

program.cs-------
`
using SourceAFIS;

namespace AFIS
{
    class afis {         
        static void Main(string[] args)
        {
            var options = new FingerprintImageOptions { Dpi = 508 };
            var probe = new FingerprintTemplate(
                new FingerprintImage(
                    160, 160, Files.ReadAllBytes("lIndex_01.png"), options));
            
            var candidate = new FingerprintTemplate(
                new FingerprintImage(
                    160, 160, Files.ReadAllBytes("lIndex_02.png"), options));
        }
    }
}
`

AFIS.csproj
`
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SourceAFIS" Version="3.13.0" />
  </ItemGroup>

   <ItemGroup>
    <EmbeddedResource Include="Resources/*.dat" />
    <EmbeddedResource Include="Resources/*.png" />
  </ItemGroup>

</Project>
`

How can I get this running ? 

Thank you!

**Comment by robertvazan** [comment]
Should be [`File.ReadAllBytes`](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readallbytes?view=net-5.0#system-io-file-readallbytes(system-string)). Thanks for letting me know about this.

```cs
var options = new FingerprintImageOptions { Dpi = 500 };

var probe = new FingerprintTemplate(
    new FingerprintImage(
        332, 533, File.ReadAllBytes("probe.dat"), options));

var candidate = new FingerprintTemplate(
    new FingerprintImage(
        320, 407, File.ReadAllBytes("candidate.dat"), options));
```
