### ISSUE TITLE
Problematic Fingerprints

### ISSUE THREAD

**Issue by StefandB76** [robertvazan/sourceafis-net#15]
I am having some issues with verifying/matching a couple of individual's fingers. I have captured multiple sample fingers from this individual and have permission to submit it for testing/software improvement purposes. The quality of the fingerprints is of a high NFIQ score, so not sure why I cannot find a match for it against its counterparts.  

[PROBLEMATIC FINGERS.zip](https://github.com/robertvazan/sourceafis-net/files/8331133/PROBLEMATIC.FINGERS.zip)

**Comment by robertvazan** [comment]
Images ASourceA1 and ASourceA2 are overimpressed. The current image enhancement in SourceAFIS cannot deal with it. Extractor produces lots of false minutiae and displaces the true ones beyond matcher's tolerances. Better image enhancement is in development, but it will not be released in the near future. My recommendation is to instruct enrollees to use appropriate pressure. If that's not possible, try to preprocess the images with custom image enhancement that is designed to correct this particular issue.
