### ISSUE TITLE
Standard image formats

### ISSUE THREAD

**Issue by jpcintegral** [robertvazan/sourceafis-net#16]
I am trying to use an image of the base "DB1_B" and none of them work with the "FingerprintImage" function.
Can you recommend me a good image batch please?
http://bias.csr.unibo.it/fvc2004/download.asp

**Comment by robertvazan** [comment]
NET version of SourceAFIS currently supports only grayscale images. Standard image format support is planned but not yet implemented. You can however look how unit tests decode images:

https://github.com/robertvazan/sourceafis-net/blob/master/SourceAFIS.Tests/FingerprintImageTest.cs

**Comment by jpcintegral** [comment]
for java if it works on all image formats ?

**Comment by robertvazan** [comment]
@jpcintegral Yes.

**Comment by robertvazan** [comment]
I just released new version that supports standard image formats. Website will be updated in te next few days.
