### ISSUE TITLE
Problem create archivo .dat 

### ISSUE THREAD

**Issue by titocontreras** [robertvazan/sourceafis-net#17]
hello,

I have 2 images in .png I want to convert them to .dat and get the height and width based on the .dat file created.
  since opening the example file probe.png has a resolution of 388 x 374; but in the example code with the .dat file it indicates 332 x 533, and there is no coincidence in these values, and for the program to work it is necessary to have the exact height and width according to the file.
How do I get that exact height and width value that sourceAfis needs so that it can be executed normally.

P.S. run the program from .net using the .dat files (gray-matching.dat and gray-probe.dat) and with the code from the page and all ok;
but if a height or width value is changed it no longer executes

**Comment by titocontreras** [comment]
hello,

I forgot to mention that I am using the version downloaded from the visual studio nuget

**Comment by robertvazan** [comment]
See here how to properly convert PNG to grayscale:

https://github.com/robertvazan/sourceafis-net/blob/b2c688bc76308f75a74aed8790ba700ee92d6238/SourceAFIS.Tests/FingerprintImageTest.cs

New version to be released in the next week or so has built-in image decoding.
