### ISSUE TITLE
Creating an image from a image byte array

### ISSUE THREAD

**Issue by GipsyA** [robertvazan/sourceafis-net#18]
Hi there

I am trying to implement this library into a web-service for a project of mine, but I am having issues testing out how to create a image from a byte array. This byte array is an image converted into bytes via the web service. However, when I try and create an image through `FingerprintImage`, I get an 'Specified argument was out of the range of valid values' error.

Below is the code I am using to try and accomplish this -

`            var options = new FingerprintImageOptions { Dpi = 500 };
            var template = new FingerprintTemplate(
                new FingerprintImage(
                    190, 265, File.ReadAllBytes(@"Images\sample.jpg"), options));
            byte[] serialized = template.ToByteArray();`

The error pop-ups on line 2. The image being used is a 190x265 picture of a fingerprint found off the net.

What would be the correct way in creating a template from an image using a byte array? Any help would be greatly appreciated!

**Comment by robertvazan** [comment]
You are trying to use grayscale API to decode JPEG. Upgrade to the latest version and use the standard image format API:

https://github.com/robertvazan/sourceafis-net/blob/master/SourceAFIS/FingerprintImage.cs

Website will be updated in the next few days to reflect the new API.

**Comment by GipsyA** [comment]
Thanks for the reply. I didn't see the updated version in the NuGet Manager. Updated the package, and used the second overload in the FingerprintImage class. Works perfectly now, from what I can tell with my samples.

Again, thanks for the reply. I look forward to seeing the edit on the website!
