### ISSUE TITLE
Create fingerprint template it's too slow

### ISSUE THREAD

**Issue by zNexTage** [robertvazan/sourceafis-net#2]
Hello, 
So, I'm using your library in a Java Android application and I'm having the following problem, the Create () function of the FingerprintTemplate method is very slow and sometimes my application closes while executing this method.

*Code snippet

    listBiometria = conSql.returnAllBiometry();

    FingerprintTemplate candidate = new FingerprintTemplate();
    candidate.dpi(500);
    candidate.create(img);

    for(Biometry biometry : listBiometria)
    {
        FingerprintTemplate probe = new FingerprintTemplate()
                .dpi(500)
                .create(biometry.getBiometria());

        score = new FingerprintMatcher()
                .index(probe)
                .match(candidate);
    }

And for my bad luck I need to use this method inside a loop, which makes things even more slow.

**Comment by robertvazan** [comment]
This is sourceafis-net project. Your issue belongs in [sourceafis-java](https://github.com/robertvazan/sourceafis-java).

Android feature extractor performance is indeed poor. Improvements are possible. Meantime it is recommended to use a recent device with solid floating-point performance.

In any case, you shouldn't be looping over images like that. Perform feature extraction after image acquisition and subsequently cache the template like the tutorial says.

**Comment by zNexTage** [comment]
Thanks for the answer and forgiveness for posting the question in the wrong place. Anyway, I will read the manual again and try to make some adjustments.
