### ISSUE TITLE
image height and width possibly wrong

### ISSUE THREAD

**Issue by Franclin-Barros** [robertvazan/sourceafis-net#24]
Hello!

I am creating an app that allows the user to add/remove minutiaes to the template. I was able to create a json from the serialized template and view it of top of the original image on the client side.

In the process, I noticed that the image width and height are not from the image scaled to 500 dpi (like said in https://sourceafis.machinezoo.com/template), but from the original image (that in my case had about 1290 dpi). Nothing THAT serious, but I think you'd like to know.

Besides, do you keep some sort of change log for SourceAFIS? I'd like to know what the differences from 3.14-net to 3.18-java are. 

Thank you so much. 
You are doing a wonderful job with SourceAFIS.

**Comment by robertvazan** [comment]
Are you sure? The code seems to correctly use dimensions of the resized image:

https://github.com/robertvazan/sourceafis-net/blob/e80a6c1a96ca11eb7c1a4f8caa2835c9a1804a3d/SourceAFIS/Engine/Extractor/FeatureExtractor.cs#L17
https://github.com/robertvazan/sourceafis-net/blob/e80a6c1a96ca11eb7c1a4f8caa2835c9a1804a3d/SourceAFIS/Engine/Extractor/FeatureExtractor.cs#L39

---

There's no changelog unfortunately. There aren't that many changes though. Just go over the commit log. And language versions are kept in sync except that some APIs might be missing from one or the other.

**Comment by Franclin-Barros** [comment]
You're right!

During the processing I was getting the dimensions from variables that held the original dimensions instead of the resized image.

🤦‍♂️
