### ISSUE TITLE
Does the resulted template support ANSI 378 and ISO ISO 19794?

### ISSUE THREAD

**Issue by Elsharif** [robertvazan/sourceafis-net#4]

**Comment by robertvazan** [comment]
Latest SourceAFIS for .NET is in alpha stage, i.e. likely broken. The last stable 1.7 branch only supports minimal ISO 19794-2:2005 import.

You can also use SourceAFIS for Java, which has full ANSI378 and minimal ISO 19794-2:2005 support:

https://sourceafis.machinezoo.com/java
https://github.com/robertvazan/sourceafis-java

**Comment by Elsharif** [comment]
Can you tell me please what "minimal" mean in ISO 19794-2:2005 ?

**Comment by robertvazan** [comment]
Only the 2005 version, only the main record format (no card formats), and only import (no export).

**Comment by Elsharif** [comment]
Sorry but I'm still confused, If I understand you correctly, If I used SourceAFIS for Java it's only supprot ISO 19794-2:2005 not 2003 ? Is it right?, and what you mean by "no card formats" ?

Please do me a favor and share with me any blog/document can enplane in detail all this points, I'm working on a new project and I want to make a right decision with a global standard.

Thanks in advance

**Comment by robertvazan** [comment]
SourceAFIS for Java also supports ANSI378 (fully). AFAIK there's no 2003 version of ISO 19794-2. There's a 2011 version that is rarely used. If you don't know what are on-card ISO 19794-2 subformats, then you don't need to worry about them.

If you are deciding on long-term storage format, I strongly recommend keeping the original fingerprint images. ANSI/ISO templates are for fringe use cases. See more here:

https://templates.machinezoo.com/discouraged

**Comment by robertvazan** [comment]
Nevertheless, if you have one of those fringe use cases and you have some budget and time, I can provide you with read-write support for ISO 19794-2. Ditto for bringing the .NET port up to the level of the Java port.

**Comment by Elsharif** [comment]
Please provide me with the detail (time & cost) to extent the .net version, my email: a.elsharif@icloud.com. 
Thank you.
