### ISSUE TITLE
SourceAFIS for .NET 1.7 Vs SourceAFIS for Java

### ISSUE THREAD

**Issue by YazanZ** [robertvazan/sourceafis-net#6]
How much time is expected to be SourceAFIS for .NET V3 complete and stable .. and is there an article explaining the features that are not available in the version 1.7 compared to the full version of Java.

Another things .. When I trying the SourceAFIS for .NET 1.7 I assign the same fingerprint to two persons then try to perform 1:1 verification
 ` float score = afis.Verify(person1, person2);`

The result is 89.67485 .. This result makes me inquire about two things:

1. Isn't the score result supposed to be 100% ?
2. By verification some another finger print the resulted score is above 100, What that mean?

Thanks in advances

**Comment by robertvazan** [comment]
There's no schedule, although obviously I would like to have it done ASAP. I am quite busy though.

Score in the 1.7 version does not mean anything. It's just higher or lower. The new version would have meaningful score just like the current Java version:

https://sourceafis.machinezoo.com/javadoc/com/machinezoo/sourceafis/FingerprintMatcher.html#match-com.machinezoo.sourceafis.FingerprintTemplate-

**Comment by YazanZ** [comment]
Thanks for your replay
I compared two same fingerprint in Java with threshold 40 the result is 79.32734691070593, What does mean?

**Comment by robertvazan** [comment]
Read the linked docs. They explain it well.
