### ISSUE TITLE
FingerPrint Template

### ISSUE THREAD

**Issue by njgith** [robertvazan/sourceafis-net#7]
With very very juicy respect I want to make a request that In  a very cheap way we can buy an arduino and a fingerprint module.
So we can get hardly a template from this combination and send to visual studio but not images. Please provide a method to compare already and newly received template from fingerprint module other wise a fingerprint scanner have too much price to get right on work. We just need to matches these template. Thanks..

This is a template which we receive from fingerprint Module:

"FFFFFFFFFFFFFFFFFF034D35300143017C000000000000000000000000000000000000000000000000000000000000000000000000000000100004008B0001010101010101010101010114D3EF01FFFFFFFF0200824214245E31A1E15E60A6905E3C9D63FF5723659F333000BF5E31517F5038533F90C8E17C78388FFA894688DA72CA443A7D3B4BB86E3CC7D87D40255929CA5C593CBDC236793F8E164B2E65B7713A8CB770C00EB775C363F769CC515760C25774874986946C1EA4554C2B907541BE981547C6413550C918355249D6954FCB13F5393CEF01FFFFFFFF02008254BC27B272BBE27368C26C1366C2D1F37445E6333ECB44533AA361B14BA8D271593CD051473F6A1145FFFFFFFFFFFFFFFFFFFFFF5041AA316AC36191454580D15549C1913CCA5DD173190EBE1B3D045E15B59C7F0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000260AEF01FFFFFFFF0200820303551C000120017A0000000000000000000000000000000000000000000000000000000000000000000000000000000F000400770000033000F3FFF3FFFFBFEFEFBBAAAAAAAAA999956555555545144444004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001193EF01FFFFFFFF0200823E12E45E2716221E7017"

**Comment by robertvazan** [comment]
This depends on .NET port of FingerprintIO:

https://fingerprintio.machinezoo.com/

I am not sure when will I find time for this. I do invest some time in the .NET port every month though. If this is urgent commercial requirement, consider paid development:

https://sourceafis.machinezoo.com/custom

**Comment by njgith** [comment]
> This depends on .NET port of FingerprintIO:
> 
> https://fingerprintio.machinezoo.com/
> 
> I am not sure when will I find time for this. I do invest some time in the .NET port every month though. If this is urgent commercial requirement, consider paid development:
> 
> https://sourceafis.machinezoo.com/custom

**Comment by robertvazan** [comment]
This is not a standard template format, at least not any of the publicly documented formats:

https://templates.machinezoo.com/

Check sensor documentation. Sensor's proprietary templates can be matched on by vendor's software. SourceAFIS will need either image, an ISO/ANSI template, or some other documented template format.

**Comment by njgith** [comment]
Thanks from depth of my ❤ for a quick and sensible reply. In fact that a fingerprint module which I bought Model(as608) it can store up to 300 template in itself but I want to make this module versatile and dynamic by getting these templates from sensor and store into database and from here you can store as many fingerprint as you wish and only thing is to remain to compare these templates other wise it  all in vain.Adafruit Fingerprint sensor library give us to enroll a fingerprint and get template these saved templates from Fingerprint module storage which is only up to 300 template but in my request we can store unlimited template into database like mysql ro sql server or any other and now need to compare these template by any library support like your library. May hope to understand my aim... Thanksss....

**Comment by njgith** [comment]
Please post one standard template that I want to see how  it look like..

**Comment by robertvazan** [comment]
I don't think Adafruit sensor produces ANSI/ISO templates. These start with "FMR" in ASCII. On-card ISO templates are harder to recognize, so on-card ISO might be hiding in there somewhere, but I don't see any signs of that.

My recommendation is to get a better sensor. Check the specs before purchase.

SourceAFIS requires .NET Standard 2.0, which means .NET Framework 4.7.2+.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by vongocminh778** [comment]
> Thanks from depth of my ❤ for a quick and sensible reply. In fact that a fingerprint module which I bought Model(as608) it can store up to 300 template in itself but I want to make this module versatile and dynamic by getting these templates from sensor and store into database and from here you can store as many fingerprint as you wish and only thing is to remain to compare these templates other wise it all in vain.Adafruit Fingerprint sensor library give us to enroll a fingerprint and get template these saved templates from Fingerprint module storage which is only up to 300 template but in my request we can store unlimited template into database like mysql ro sql server or any other and now need to compare these template by any library support like your library. May hope to understand my aim... Thanksss....

You need to get raw photos from the AS608 sensor before you want to continue comparing fingerprints.
