### ISSUE TITLE
Extract image

### ISSUE THREAD

**Issue by vongocminh778** [robertvazan/sourceafis-net#9]
I am trying to bring this txt file to extract the characteristics but seem to have something I can't do.
[tri_test.txt](https://github.com/robertvazan/sourceafis-net/files/6595469/tri_test.txt)(192x192 508dpi)

**Comment by robertvazan** [comment]
Could you post it as an image?

**Comment by vongocminh778** [comment]
My image is the byte form as the file I attached above. How can I extract the characteristics from the image with PNG, JPEG .... I only see file.dat (byte), I don't know what have you handled the image before? Please give me a guide. Thank you.

**Comment by robertvazan** [comment]
Could you at least post code you have tried to use to read the image?

**Comment by vongocminh778** [comment]
I use this code to extract featured

`string file_name = "SUM_CM04";
            Afis = new AfisEngine();
            List<MyPerson> database = new List<MyPerson>();
            string _path1 = @"E:\MINHVO\DATABASE\images\" + file_name;  
            var files = Directory.GetFiles(_path1, "*.tif");
            foreach (var i in files)
            {
                string FileName = System.IO.Path.GetFileNameWithoutExtension(i);
                database.Add(Enroll(Path.Combine(_path1, FileName + ".tif"), FileName));

            }

            using (Stream stream = File.Open(@"E:\MINHVO\DATABASE\xml\" + file_name +"_2923" + ".xml", FileMode.Create))
            {
                var serializer = new XmlSerializer(typeof(List<MyPerson>));
                serializer.Serialize(stream, database);
            }
            Console.WriteLine("Done!!!");
            Console.ReadKey();`

` static MyPerson Enroll(string filename, string name)
        {
            try
            {
                Console.WriteLine("Enrolling {0}...", name);
                Fingerprint fp = new Fingerprint();
                Console.WriteLine(" Loading image from {0}...", filename);
                fp.AsBitmap = new Bitmap(Bitmap.FromFile(filename));
                Console.WriteLine(" Image size = {0} x {1} (width x height)", fp.Image.GetLength(1), fp.Image.GetLength(0));
                MyPerson person = new MyPerson();
                person.Name = name;
                person.Fingerprints.Add(fp);
                Console.WriteLine(" Extracting template...");
                Afis.Extract(person);
                byte[] template = fp.Template;
                Console.WriteLine(" Template size = {0} bytes", fp.Template.Length);
                return person;
            }
            catch
            {
                MyPerson person = new MyPerson();
                return person;
            }

        }`
But it seems that Party 3.3 I don't see it, how can I extract featured in the new version?

**Comment by robertvazan** [comment]
When you first posted here, it looked like you are observing poor feature extractor performance, but now it is clear you have not run it yet, because you do not have the code updated to the new version.

Look in [FingerprintImageTest](https://github.com/robertvazan/sourceafis-net/blob/master/SourceAFIS.Tests/FingerprintImageTest.cs) for an example of how to get `FingerprintImage` from bitmap. Once you have that (and considering you have posted the grayscale image here, it looks like you do), follow the tutorial:

https://sourceafis.machinezoo.com/net

**Comment by vongocminh778** [comment]
Thanks for your support. So how does the new version change with the old version 1.7?

**Comment by robertvazan** [comment]
The new version has API and most features in line with latest Java version. Most importantly, it is under active development contrary to the obsolete 1.7 version.

**Comment by vongocminh778** [comment]
Thanks you. Have a nice day!

Vào Th 2, 7 thg 6, 2021 vào lúc 14:05 Robert Važan <
***@***.***> đã viết:
